language: node_js
node_js:
  - "5"
before_script:
  - npm install -g jasmine-node
 
 # TODO
 # travis runs npm test by default
 # npm version bump
 # push version bump to github?
 # run npm publish using secret npm creds
 